-d C:\Yoga_share\Source Control\Tang_Nano_20K\HelloWorld\blink\impl\gwsynthesis\blink.vg
-p GW2AR-18C-QFN88-8
-pn GW2AR-LV18QN88C8/I7
-cst C:\Yoga_share\Source Control\Tang_Nano_20K\HelloWorld\blink\src\blink.cst
-cfg C:\Yoga_share\Source Control\Tang_Nano_20K\HelloWorld\blink\impl\pnr\device.cfg
-sdc C:\Yoga_share\Source Control\Tang_Nano_20K\HelloWorld\blink\src\blink.sdc
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
